name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb3c579aca06260f0a27164e97a6d27542bf13a708a7dc92bb67e716e54b004b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
