name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c97c056d48a1944ecce1bd7ca9ee4bd419275e69bef587cc674e14836fd4b1cd"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
