name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f2fe9eca8b33ba37e1704723dee53e6e283c17c07832e58b1bed62bcbe18519"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
